version: '3'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./client
    ports: 
      - "80:80"
    depends_on:
      - backend
  
  db:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
